/**
 * Curated Lucide icon set for user-created labels, grouped into the categories
 * surfaced in the "New Label" modal. Each icon appears in exactly one category.
 *
 * Icons are referenced by their Lucide PascalCase name (e.g. "Coffee"), which is
 * what we persist in `tags.icon`. Resolve a stored name back to a component with
 * `getLabelIcon(name)`.
 */
import {
  Accessibility,
  Activity,
  Anchor,
  Angry,
  Annoyed,
  Apple,
  Armchair,
  Baby,
  Backpack,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Bird,
  Building,
  Building2,
  Bug,
  Bus,
  Cake,
  Car,
  Caravan,
  Carrot,
  Castle,
  Cat,
  Cherry,
  Church,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Clover,
  Coffee,
  Compass,
  Contact,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  CupSoda,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Droplets,
  Drumstick,
  Dumbbell,
  Earth,
  EggFried,
  Factory,
  Fish,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Ghost,
  Gift,
  Globe,
  Goal,
  Grape,
  Handshake,
  HeartHandshake,
  Hospital,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  LaptopMinimalCheck,
  Laugh,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Microwave,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Package,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Rabbit,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shrub,
  Skull,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sprout,
  Squirrel,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Tent,
  Theater,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Turtle,
  Umbrella,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Wheat,
  Wind,
  Wine,
  Worm,
} from "lucide-react-native";

export type LabelIconCategory = {
  key: string;
  title: string;
  icons: string[];
};

/** Flat lookup from persisted icon name → Lucide component. */
export const LABEL_ICONS: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  Anchor,
  Angry,
  Annoyed,
  Apple,
  Armchair,
  Baby,
  Backpack,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Bird,
  Building,
  Building2,
  Bug,
  Bus,
  Cake,
  Car,
  Caravan,
  Carrot,
  Castle,
  Cat,
  Cherry,
  Church,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Clover,
  Coffee,
  Compass,
  Contact,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  CupSoda,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Droplets,
  Drumstick,
  Dumbbell,
  Earth,
  EggFried,
  Factory,
  Fish,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Ghost,
  Gift,
  Globe,
  Goal,
  Grape,
  Handshake,
  HeartHandshake,
  Hospital,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  LaptopMinimalCheck,
  Laugh,
  Leaf,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Microwave,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Package,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Rabbit,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shrub,
  Skull,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sprout,
  Squirrel,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Tent,
  Theater,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Turtle,
  Umbrella,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Wheat,
  Wind,
  Wine,
  Worm,
};

/** Default icon shown before the user picks one (and the resolution fallback). */
export const DEFAULT_LABEL_ICON = "Tag";

export const LABEL_ICON_CATEGORIES: LabelIconCategory[] = [
  {
    key: "animals",
    title: "Animals",
    icons: [
      "Dog",
      "Cat",
      "Fish",
      "Bird",
      "Rabbit",
      "Turtle",
      "Squirrel",
      "Snail",
      "PawPrint",
      "Bug",
      "Rat",
      "Worm",
    ],
  },
  {
    key: "buildings",
    title: "Buildings",
    icons: [
      "Building",
      "Building2",
      "Hotel",
      "Church",
      "Castle",
      "Factory",
      "Store",
      "Warehouse",
      "School",
      "Hospital",
      "Landmark",
      "Theater",
    ],
  },
  {
    key: "emoji",
    title: "Emoji",
    icons: [
      "Smile",
      "SmilePlus",
      "Laugh",
      "Meh",
      "Annoyed",
      "Frown",
      "Angry",
      "Ghost",
      "Skull",
      "PartyPopper",
    ],
  },
  {
    key: "foodBeverage",
    title: "Food & Beverage",
    icons: [
      "Coffee",
      "CupSoda",
      "Beer",
      "Wine",
      "Martini",
      "Milk",
      "Pizza",
      "Sandwich",
      "Soup",
      "Salad",
      "Beef",
      "Drumstick",
      "EggFried",
      "Croissant",
      "Cake",
      "Cookie",
      "Donut",
      "IceCreamCone",
      "Popcorn",
      "Apple",
      "Cherry",
      "Grape",
      "Carrot",
      "Wheat",
      "UtensilsCrossed",
    ],
  },
  {
    key: "home",
    title: "Home",
    icons: [
      "House",
      "DoorOpen",
      "DoorClosed",
      "Bed",
      "BedDouble",
      "Sofa",
      "Armchair",
      "Bath",
      "Lamp",
      "LampDesk",
      "CookingPot",
      "Microwave",
      "Refrigerator",
      "WashingMachine",
      "Plug",
      "Key",
    ],
  },
  {
    key: "nature",
    title: "Nature",
    icons: [
      "Trees",
      "TreePine",
      "TreeDeciduous",
      "Shrub",
      "Leaf",
      "Clover",
      "Sprout",
      "Flower",
      "Flower2",
      "Mountain",
      "MountainSnow",
      "WavesHorizontal",
    ],
  },
  {
    key: "people",
    title: "People",
    icons: [
      "User",
      "UserRound",
      "Users",
      "UsersRound",
      "UserPlus",
      "Baby",
      "PersonStanding",
      "Accessibility",
      "Handshake",
      "HeartHandshake",
      "Contact",
    ],
  },
  {
    key: "seasons",
    title: "Seasons",
    icons: [
      "Snowflake",
      "Sunrise",
      "Sunset",
      "ThermometerSun",
      "ThermometerSnowflake",
    ],
  },
  {
    key: "shopping",
    title: "Shopping",
    icons: [
      "ShoppingCart",
      "ShoppingBag",
      "ShoppingBasket",
      "Tag",
      "Gift",
      "Shirt",
      "Package",
      "Receipt",
      "BadgePercent",
      "CreditCard",
      "Wallet",
      "Banknote",
    ],
  },
  {
    key: "sport",
    title: "Sport",
    icons: [
      "Dumbbell",
      "Bike",
      "Footprints",
      "Volleyball",
      "Goal",
      "Target",
      "Trophy",
      "Medal",
      "Activity",
    ],
  },
  {
    key: "sustainability",
    title: "Sustainability",
    icons: [
      "Recycle",
      "BatteryCharging",
      "Lightbulb",
      "Globe",
      "Earth",
      "Fuel",
      "Trash2",
    ],
  },
  {
    key: "travel",
    title: "Travel",
    icons: [
      "Plane",
      "Car",
      "Bus",
      "TrainFront",
      "TramFront",
      "Ship",
      "Sailboat",
      "Anchor",
      "Caravan",
      "Tent",
      "Backpack",
      "Luggage",
      "Compass",
      "Map",
      "MapPin",
    ],
  },
  {
    key: "weather",
    title: "Weather",
    icons: [
      "Sun",
      "Moon",
      "Cloud",
      "CloudRain",
      "CloudDrizzle",
      "CloudSnow",
      "CloudLightning",
      "CloudFog",
      "Wind",
      "Droplets",
      "Umbrella",
      "Rainbow",
      "Tornado",
    ],
  },
];

// Order the categories surface in the single icon grid. Categories not listed
// here are appended afterwards in their declared order.
const LABEL_ICON_CATEGORY_ORDER = [
  "foodBeverage",
  "nature",
  "weather",
  "home",
  "animals",
  "sport",
  "travel",
  "buildings",
];

/** All label icons as a single ordered list, ready for one flat grid. */
export const LABEL_ICON_NAMES: string[] = [
  ...LABEL_ICON_CATEGORY_ORDER,
  ...LABEL_ICON_CATEGORIES.map((c) => c.key).filter(
    (key) => !LABEL_ICON_CATEGORY_ORDER.includes(key),
  ),
]
  .map((key) => LABEL_ICON_CATEGORIES.find((c) => c.key === key))
  .filter((c): c is LabelIconCategory => c !== undefined)
  .flatMap((c) => c.icons);

export const getLabelIcon = (name?: string | null): LucideIcon =>
  (name ? LABEL_ICONS[name] : undefined) ??
  LABEL_ICONS[DEFAULT_LABEL_ICON] ??
  Tag;
