/**
 * Curated Lucide icon set for user-created labels, grouped into the categories
 * surfaced in the "New Label" modal. Each icon appears in exactly one category.
 *
 * Icons are referenced by their Lucide PascalCase name (e.g. "Coffee"), which is
 * what we persist in `tags.icon`. Resolve a stored name back to a component with
 * `getLabelIcon(name)`.
 */
import {
  Accessibility,
  Activity,
  Anchor,
  createLucideIcon,
  Angry,
  Annoyed,
  Apple,
  Armchair,
  Baby,
  Backpack,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Bird,
  Building,
  Building2,
  Bug,
  Bus,
  Cake,
  Car,
  Caravan,
  Carrot,
  Castle,
  Cat,
  Cherry,
  Church,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Clover,
  Coffee,
  Compass,
  Contact,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  CupSoda,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Droplets,
  Drumstick,
  Dumbbell,
  Earth,
  EggFried,
  Factory,
  Fish,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Ghost,
  Gift,
  Globe,
  Goal,
  Grape,
  Handshake,
  Haze,
  HeartHandshake,
  Hospital,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  LaptopMinimalCheck,
  Laugh,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Microwave,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Package,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Rabbit,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shrub,
  Skull,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sprout,
  Squirrel,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Tent,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Turtle,
  Umbrella,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Wheat,
  Wind,
  Wine,
  Worm,
  Zap,
} from "lucide-react-native";

import {
  avocado,
  babyPacifier,
  bacon,
  bagHand,
  barn,
  baseball,
  basketball,
  beachBall,
  bee,
  bottlePlastic,
  bowling,
  burger,
  butterfly,
  cabin,
  cactus,
  cardCredit,
  carton,
  catBig,
  cheese,
  cocktail,
  coffeeBean,
  coinsStack,
  crab,
  cupSaucer,
  deskLamp,
  dishwasher,
  dress,
  elephant,
  faceAlien,
  farm,
  faucet,
  flippers,
  flowerLotus,
  flowerPot,
  flowerRose,
  flowerTulip,
  football,
  forkKnife,
  foxFaceTail,
  frogFace,
  garlic,
  gemRing,
  glassesSun,
  golfDriver,
  grapes,
  hatBeanie,
  hatTop,
  hedgehog,
  hockey,
  horseHead,
  hotDog,
  houseManor,
  iceSkate,
  igloo,
  iron,
  jacket,
  kettle,
  kiwi,
  lemon,
  lifeJacket,
  lightSwitch,
  luggageCabin,
  maskSnorkel,
  mug,
  mustache,
  onion,
  owl,
  palmtreeIslandSun,
  pancakes,
  peace,
  peach,
  pear,
  penguin,
  pepperChilli,
  pie,
  pig,
  pillow,
  planet,
  pond,
  pram,
  pretzel,
  pumpkin,
  refrigeratorFreezer,
  rugby,
  sausage,
  scarf,
  shark,
  shirtT,
  shower,
  skirt,
  skis,
  sneaker,
  snowboard,
  snowman,
  soccerBall,
  socketEu,
  socks,
  spider,
  steeringWheel,
  strawberry,
  stroller,
  sunloungerParasolSun,
  surfboard,
  sushi,
  sweater,
  tennisBall,
  tennisRacket,
  tie,
  toast,
  toaster,
  toolbox,
  treesForest,
  trousers,
  tuxedo,
  unicornHead,
  waffle,
  wardrobe,
  watermelon,
  whale,
  windmill,
  yinYang,
} from "@lucide/lab";

/**
 * Curated Lucide Lab icons (the experimental companion set). Each node is wrapped
 * into a `LucideIcon` so it renders identically to a core icon. Keys are prefixed
 * with `Lab` to guarantee they never collide with a core Lucide icon name — these
 * keys are what we persist in `tags.icon`.
 */
const LAB_ICON_NODES = {
  LabAvocado: avocado,
  LabBabyPacifier: babyPacifier,
  LabBacon: bacon,
  LabBagHand: bagHand,
  LabBarn: barn,
  LabBaseball: baseball,
  LabBasketball: basketball,
  LabBeachBall: beachBall,
  LabBee: bee,
  LabBottlePlastic: bottlePlastic,
  LabBowling: bowling,
  LabBurger: burger,
  LabButterfly: butterfly,
  LabCabin: cabin,
  LabCactus: cactus,
  LabCardCredit: cardCredit,
  LabCarton: carton,
  LabCatBig: catBig,
  LabCheese: cheese,
  LabCocktail: cocktail,
  LabCoffeeBean: coffeeBean,
  LabCoinsStack: coinsStack,
  LabCrab: crab,
  LabCupSaucer: cupSaucer,
  LabDeskLamp: deskLamp,
  LabDishwasher: dishwasher,
  LabDress: dress,
  LabElephant: elephant,
  LabFaceAlien: faceAlien,
  LabFarm: farm,
  LabFaucet: faucet,
  LabFlippers: flippers,
  LabFlowerLotus: flowerLotus,
  LabFlowerPot: flowerPot,
  LabFlowerRose: flowerRose,
  LabFlowerTulip: flowerTulip,
  LabFootball: football,
  LabForkKnife: forkKnife,
  LabFoxFaceTail: foxFaceTail,
  LabFrogFace: frogFace,
  LabGarlic: garlic,
  LabGemRing: gemRing,
  LabGlassesSun: glassesSun,
  LabGolfDriver: golfDriver,
  LabGrapes: grapes,
  LabHatBeanie: hatBeanie,
  LabHatTop: hatTop,
  LabHedgehog: hedgehog,
  LabHockey: hockey,
  LabHorseHead: horseHead,
  LabHotDog: hotDog,
  LabHouseManor: houseManor,
  LabIceSkate: iceSkate,
  LabIgloo: igloo,
  LabIron: iron,
  LabJacket: jacket,
  LabKettle: kettle,
  LabKiwi: kiwi,
  LabLemon: lemon,
  LabLifeJacket: lifeJacket,
  LabLightSwitch: lightSwitch,
  LabLuggageCabin: luggageCabin,
  LabMaskSnorkel: maskSnorkel,
  LabMug: mug,
  LabMustache: mustache,
  LabOnion: onion,
  LabOwl: owl,
  LabPalmtreeIslandSun: palmtreeIslandSun,
  LabPancakes: pancakes,
  LabPeace: peace,
  LabPeach: peach,
  LabPear: pear,
  LabPenguin: penguin,
  LabPepperChilli: pepperChilli,
  LabPie: pie,
  LabPig: pig,
  LabPillow: pillow,
  LabPlanet: planet,
  LabPond: pond,
  LabPram: pram,
  LabPretzel: pretzel,
  LabPumpkin: pumpkin,
  LabRefrigeratorFreezer: refrigeratorFreezer,
  LabRugby: rugby,
  LabSausage: sausage,
  LabScarf: scarf,
  LabShark: shark,
  LabShirtT: shirtT,
  LabShower: shower,
  LabSkirt: skirt,
  LabSkis: skis,
  LabSneaker: sneaker,
  LabSnowboard: snowboard,
  LabSnowman: snowman,
  LabSoccerBall: soccerBall,
  LabSocketEu: socketEu,
  LabSocks: socks,
  LabSpider: spider,
  LabSteeringWheel: steeringWheel,
  LabStrawberry: strawberry,
  LabStroller: stroller,
  LabSunloungerParasolSun: sunloungerParasolSun,
  LabSurfboard: surfboard,
  LabSushi: sushi,
  LabSweater: sweater,
  LabTennisBall: tennisBall,
  LabTennisRacket: tennisRacket,
  LabTie: tie,
  LabToast: toast,
  LabToaster: toaster,
  LabToolbox: toolbox,
  LabTreesForest: treesForest,
  LabTrousers: trousers,
  LabTuxedo: tuxedo,
  LabUnicornHead: unicornHead,
  LabWaffle: waffle,
  LabWardrobe: wardrobe,
  LabWatermelon: watermelon,
  LabWhale: whale,
  LabWindmill: windmill,
  LabYinYang: yinYang,
};

const LAB_ICONS: Record<string, LucideIcon> = Object.fromEntries(
  Object.entries(LAB_ICON_NODES).map(([name, node]) => [
    name,
    createLucideIcon(name, node),
  ]),
);

export type LabelIconCategory = {
  key: string;
  title: string;
  icons: string[];
};

/** Flat lookup from persisted icon name → Lucide component. */
export const LABEL_ICONS: Record<string, LucideIcon> = {
  Accessibility,
  Activity,
  Anchor,
  Angry,
  Annoyed,
  Apple,
  Armchair,
  Baby,
  Backpack,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bike,
  Bird,
  Building,
  Building2,
  Bug,
  Bus,
  Cake,
  Car,
  Caravan,
  Carrot,
  Castle,
  Cat,
  Cherry,
  Church,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Clover,
  Coffee,
  Compass,
  Contact,
  Cookie,
  CookingPot,
  CreditCard,
  Croissant,
  CupSoda,
  Dog,
  Donut,
  DoorClosed,
  DoorOpen,
  Droplets,
  Drumstick,
  Dumbbell,
  Earth,
  EggFried,
  Factory,
  Fish,
  Flower,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Ghost,
  Gift,
  Globe,
  Goal,
  Grape,
  Handshake,
  Haze,
  HeartHandshake,
  Hospital,
  Hotel,
  House,
  IceCreamCone,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Laptop,
  LaptopMinimalCheck,
  Laugh,
  Leaf,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Martini,
  Medal,
  Meh,
  Microwave,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Package,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Rabbit,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Sailboat,
  Salad,
  Sandwich,
  School,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shrub,
  Skull,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Sprout,
  Squirrel,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Target,
  Tent,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Tornado,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Turtle,
  Umbrella,
  User,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Wheat,
  Wind,
  Wine,
  Worm,
  Zap,
  ...LAB_ICONS,
};

/** Default icon shown before the user picks one (and the resolution fallback). */
export const DEFAULT_LABEL_ICON = "Tag";

export const LABEL_ICON_CATEGORIES: LabelIconCategory[] = [
  {
    key: "animals",
    title: "Animals",
    icons: [
      "Dog",
      "Cat",
      "Fish",
      "Bird",
      "Rabbit",
      "Turtle",
      "Squirrel",
      "Snail",
      "PawPrint",
      "Bug",
      "Rat",
      "Worm",
      "LabCatBig",
      "LabFoxFaceTail",
      "LabHorseHead",
      "LabElephant",
      "LabHedgehog",
      "LabPenguin",
      "LabOwl",
      "LabPig",
      "LabWhale",
      "LabShark",
      "LabCrab",
      "LabFrogFace",
      "LabSpider",
      "LabBee",
      "LabButterfly",
      "LabUnicornHead",
    ],
  },
  {
    key: "buildings",
    title: "Buildings",
    icons: [
      "Building",
      "Building2",
      "Hotel",
      "Church",
      "Castle",
      "Factory",
      "Store",
      "Warehouse",
      "School",
      "Hospital",
      "Landmark",
      "Theater",
      "LabHouseManor",
      "LabBarn",
      "LabCabin",
      "LabFarm",
      "LabIgloo",
    ],
  },
  {
    key: "emoji",
    title: "Emoji",
    icons: [
      "Smile",
      "SmilePlus",
      "Laugh",
      "Meh",
      "Annoyed",
      "Frown",
      "Angry",
      "Ghost",
      "Skull",
      "PartyPopper",
      "LabFaceAlien",
      "LabPeace",
      "LabYinYang",
    ],
  },
  {
    key: "foodBeverage",
    title: "Food & Beverage",
    icons: [
      "Coffee",
      "CupSoda",
      "Beer",
      "Wine",
      "Martini",
      "Milk",
      "Pizza",
      "Sandwich",
      "Soup",
      "Salad",
      "Beef",
      "Drumstick",
      "EggFried",
      "Croissant",
      "Cake",
      "Cookie",
      "Donut",
      "IceCreamCone",
      "Popcorn",
      "Apple",
      "Cherry",
      "Grape",
      "Carrot",
      "Wheat",
      "UtensilsCrossed",
      "LabBurger",
      "LabHotDog",
      "LabSausage",
      "LabBacon",
      "LabCheese",
      "LabPretzel",
      "LabSushi",
      "LabPancakes",
      "LabWaffle",
      "LabToast",
      "LabPie",
      "LabAvocado",
      "LabStrawberry",
      "LabWatermelon",
      "LabLemon",
      "LabPeach",
      "LabPear",
      "LabGrapes",
      "LabKiwi",
      "LabOnion",
      "LabGarlic",
      "LabPepperChilli",
      "LabPumpkin",
      "LabCoffeeBean",
      "LabCocktail",
      "LabMug",
      "LabCupSaucer",
      "LabForkKnife",
    ],
  },
  {
    key: "home",
    title: "Home",
    icons: [
      "House",
      "DoorOpen",
      "DoorClosed",
      "Bed",
      "BedDouble",
      "Sofa",
      "Armchair",
      "Bath",
      "Lamp",
      "LampDesk",
      "CookingPot",
      "Microwave",
      "Refrigerator",
      "WashingMachine",
      "Plug",
      "Key",
      "LabDeskLamp",
      "LabLightSwitch",
      "LabKettle",
      "LabToaster",
      "LabDishwasher",
      "LabRefrigeratorFreezer",
      "LabFaucet",
      "LabShower",
      "LabWardrobe",
      "LabIron",
      "LabPillow",
      "LabToolbox",
    ],
  },
  {
    key: "nature",
    title: "Nature",
    icons: [
      "Trees",
      "TreePine",
      "TreeDeciduous",
      "Shrub",
      "Leaf",
      "Clover",
      "Sprout",
      "Flower",
      "Flower2",
      "Mountain",
      "MountainSnow",
      "WavesHorizontal",
      "LabCactus",
      "LabTreesForest",
      "LabFlowerLotus",
      "LabFlowerRose",
      "LabFlowerTulip",
      "LabFlowerPot",
      "LabPond",
    ],
  },
  {
    key: "people",
    title: "People",
    icons: [
      "User",
      "UserRound",
      "Users",
      "UsersRound",
      "UserPlus",
      "Baby",
      "PersonStanding",
      "Accessibility",
      "Handshake",
      "HeartHandshake",
      "Contact",
      "LabDress",
      "LabTuxedo",
      "LabJacket",
      "LabSweater",
      "LabShirtT",
      "LabTrousers",
      "LabSkirt",
      "LabSneaker",
      "LabSocks",
      "LabScarf",
      "LabHatTop",
      "LabHatBeanie",
      "LabGlassesSun",
      "LabGemRing",
      "LabTie",
      "LabMustache",
      "LabStroller",
      "LabPram",
      "LabBabyPacifier",
    ],
  },
  {
    key: "seasons",
    title: "Seasons",
    icons: [
      "Snowflake",
      "Sunrise",
      "Sunset",
      "ThermometerSun",
      "ThermometerSnowflake",
      "LabSnowman",
    ],
  },
  {
    key: "shopping",
    title: "Shopping",
    icons: [
      "ShoppingCart",
      "ShoppingBag",
      "ShoppingBasket",
      "Tag",
      "Gift",
      "Shirt",
      "Package",
      "Receipt",
      "BadgePercent",
      "CreditCard",
      "Wallet",
      "Banknote",
      "LabBagHand",
      "LabCardCredit",
      "LabCoinsStack",
    ],
  },
  {
    key: "sport",
    title: "Sport",
    icons: [
      "Dumbbell",
      "Bike",
      "Footprints",
      "Volleyball",
      "Goal",
      "Target",
      "Trophy",
      "Medal",
      "Activity",
      "LabSoccerBall",
      "LabBasketball",
      "LabBaseball",
      "LabFootball",
      "LabRugby",
      "LabTennisBall",
      "LabTennisRacket",
      "LabBeachBall",
      "LabBowling",
      "LabGolfDriver",
      "LabHockey",
      "LabIceSkate",
      "LabSkis",
      "LabSnowboard",
      "LabSurfboard",
    ],
  },
  {
    key: "sustainability",
    title: "Sustainability",
    icons: [
      "Recycle",
      "BatteryCharging",
      "Lightbulb",
      "Globe",
      "Earth",
      "Fuel",
      "Trash2",
      "LabWindmill",
      "LabPlanet",
      "LabBottlePlastic",
      "LabCarton",
      "LabSocketEu",
    ],
  },
  {
    key: "travel",
    title: "Travel",
    icons: [
      "Plane",
      "Car",
      "Bus",
      "TrainFront",
      "TramFront",
      "Ship",
      "Sailboat",
      "Anchor",
      "Caravan",
      "Tent",
      "Backpack",
      "Luggage",
      "Compass",
      "Map",
      "MapPin",
      "LabLuggageCabin",
      "LabSteeringWheel",
      "LabLifeJacket",
      "LabFlippers",
      "LabMaskSnorkel",
      "LabSunloungerParasolSun",
      "LabPalmtreeIslandSun",
    ],
  },
  {
    key: "weather",
    title: "Weather",
    icons: [
      "Sun",
      "Moon",
      "Cloud",
      "CloudSun",
      "CloudMoon",
      "CloudRain",
      "CloudSunRain",
      "CloudMoonRain",
      "CloudDrizzle",
      "CloudSnow",
      "CloudHail",
      "CloudLightning",
      "CloudFog",
      "Haze",
      "Wind",
      "Droplets",
      "Umbrella",
      "Rainbow",
      "Tornado",
      "Zap",
      "Thermometer",
    ],
  },
];

// Order the categories surface in the single icon grid. Categories not listed
// here are appended afterwards in their declared order.
const LABEL_ICON_CATEGORY_ORDER = [
  "foodBeverage",
  "nature",
  "weather",
  "home",
  "animals",
  "sport",
  "travel",
  "buildings",
];

/** All label icons as a single ordered list, ready for one flat grid. */
export const LABEL_ICON_NAMES: string[] = [
  ...LABEL_ICON_CATEGORY_ORDER,
  ...LABEL_ICON_CATEGORIES.map((c) => c.key).filter(
    (key) => !LABEL_ICON_CATEGORY_ORDER.includes(key),
  ),
]
  .map((key) => LABEL_ICON_CATEGORIES.find((c) => c.key === key))
  .filter((c): c is LabelIconCategory => c !== undefined)
  .flatMap((c) => c.icons);

export const getLabelIcon = (name?: string | null): LucideIcon =>
  (name ? LABEL_ICONS[name] : undefined) ??
  LABEL_ICONS[DEFAULT_LABEL_ICON] ??
  Tag;
